version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  swiftlint: ngs/swiftlint@0.0.1

jobs:
  build:
    macos:
      xcode: "14.0.1"
    working_directory: /Users/distiller/project
    environment:
      SCAN_DEVICE: iPhone 14
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: build_and_test
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 180
      FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: spm-cache-{{ checksum "Package.resolved" }}
      - ruby/install-deps
      - run:
          name: Install missing gems
          command: bundle install
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - save_cache:
          paths:
            - SourcePackages/
          key: spm-cache-{{ checksum "Package.resolved" }}
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
