version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0

jobs:
  build:
    macos:
      xcode: "13.4.1"
    working_directory: /Users/distiller/project
    environment:
      SCAN_DEVICE: iPhone 13
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 180
      FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
