# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run tests under NoteApp target"
  lane :build_and_test do
    run_test(
      scheme: "NoteApp",
      device: "iPhone 14"
    )
  end
end
